### ISSUE TITLE
New UI (2.0) not working with Equipment & Quick slots

### ISSUE THREAD

**Issue by lfvideos** [matias-kovero/BetterUI#3]
I've been using this two addons for a while now, they've worked together fine until this new version. Now it shows the quick slots vertically next to both Stamina and Health bars. 

![quick slots](https://user-images.githubusercontent.com/37132073/114615938-e148a400-9c6b-11eb-9193-0a3602da3a1e.png)

**Comment by matias-kovero** [comment]
Thank you, this will be fixed on the next patch.

**Comment by ate0ate** [comment]
Kinda related to this, kinda not, but Is there any way to separate the quickslots from the health bar? The new bars for HP and Stamina are really nice and fit very well on top of each other to maximize screen space. Them being flipped from vertical to horizontal makes things even cleaner but then having the quickslots linked to them in vertical configuration makes it hard to get a clean minimalist look while having them visible onscreen at all. Love the changes overall. Got rid of the Custom UI mod completely now that this covers things nicely.

**Comment by matias-kovero** [comment]
@ate0ate Going to add support to rotate these bars. 
Also trying to detach the Quickslot from the bars, so you could position it individually.

However, I'm not sure if I understand right, you are looking to rotate the QuickSlots as well?

**Comment by ate0ate** [comment]
@matias-kovero I apologize for my lack of clarity. Separating the two is more than enough. 
I was just trying to explain that what I was having trouble with was that the two linked elements (HP Bar and QuickSlots) had opposite configurations rather than both being laid out horizontally or both vertically making it a bit tricky to squeeze things together neatly. 
I just tried the update you released and that is absolutely perfect. You went above and beyond! 
Thank you very much for adjusting things.
